apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-deployment
  name: go-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
